on:
  push:
    branches:
      - main
    paths:
      - Cargo.lock
      - crates/lib/src/client.rs
      - crates/lib/src/dist_pkgx_dev.pem
  pull_request:
    paths:
      - Cargo.lock
      - crates/lib/src/client.rs
      - crates/lib/src/dist_pkgx_dev.pem
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:buster-slim
    steps:
      - uses: actions/checkout@v4
      - run: apt-get update && apt-get install -y curl gcc perl make
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          path: ./target/release/pkgx
          name: pkgx

  test:
    needs: build
    runs-on: ubuntu-latest
    container: debian:buster-slim
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: pkgx

      - run: chmod +x ./pkgx

      - run: ./pkgx +git
